package com.portfolio.squadmate.domain;

public enum Position {
    GOALKEEPER,
    CENTER_BACK,
    LEFT_BACK,
    RIGHT_BACK,
    LEFT_WING_BACK,
    RIGHT_WING_BACK,
    DEFENSIVE_MIDFIELDER,
    CENTRAL_MIDFIELDER,
    ATTACKING_MIDFIELDER,
    LEFT_MIDFIELDER,
    RIGHT_MIDFIELDER,
    LEFT_WINGER,
    RIGHT_WINGER,
    SECOND_STRIKER,
    STRIKER;
}
